import { Business, Customer, Product, Supplier, Sale, Receivable, Alert, ModelTelemetry } from '@/types';

export const initialBusiness: Business = {
  id: 'biz_001',
  name: 'Sharma Kirana & General Store',
  ownerName: 'Maanas Pandey',
  phone: '+91 98765 43210',
  businessType: 'Kirana & FMCG Retail',
  currency: '₹',
  address: 'Shop #14, Okhla Phase III, Near IIIT Delhi, New Delhi - 110020',
  gstin: '07AAAAA0000A1Z5',
  languagePreference: 'hinglish',
  createdAt: '2026-01-15T08:00:00Z',
};

export const initialProducts: Product[] = [
  {
    id: 'prod_rice',
    name: 'Basmati Rice Premium',
    nameHindi: 'बासमती चावल',
    category: 'Grains & Cereals',
    sku: 'GRN-RICE-01',
    quantity: 100,
    unit: 'kg',
    purchasePrice: 48,
    sellingPrice: 60,
    reorderLevel: 25,
    supplierName: 'Sharma Wholesale Agro Mandi',
    supplierId: 'sup_001',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_sugar',
    name: 'Refined Sugar M-Grade',
    nameHindi: 'सफेद चीनी',
    category: 'Staples',
    sku: 'STP-SUG-02',
    quantity: 18, // Intentionally low for alert
    unit: 'kg',
    purchasePrice: 38,
    sellingPrice: 46,
    reorderLevel: 25,
    supplierName: 'Sharma Wholesale Agro Mandi',
    supplierId: 'sup_001',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_atta',
    name: 'Chakki Fresh Atta',
    nameHindi: 'गेहूं का आटा',
    category: 'Flour',
    sku: 'FLR-ATT-03',
    quantity: 120,
    unit: 'kg',
    purchasePrice: 32,
    sellingPrice: 42,
    reorderLevel: 30,
    supplierName: 'Sharma Wholesale Agro Mandi',
    supplierId: 'sup_001',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_oil',
    name: 'Fortune Mustard Oil Kacchi Ghani',
    nameHindi: 'सरसों का तेल',
    category: 'Edible Oils',
    sku: 'OIL-MUS-04',
    quantity: 14,
    unit: 'litre',
    purchasePrice: 135,
    sellingPrice: 165,
    reorderLevel: 10,
    supplierName: 'Gupta Edible Oils & FMCG',
    supplierId: 'sup_002',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_dal',
    name: 'Toor Dal Desi Unpolished',
    nameHindi: 'अरहर / तूर दाल',
    category: 'Pulses',
    sku: 'PLS-TOR-05',
    quantity: 8, // Below reorder level
    unit: 'kg',
    purchasePrice: 135,
    sellingPrice: 170,
    reorderLevel: 15,
    supplierName: 'Sharma Wholesale Agro Mandi',
    supplierId: 'sup_001',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_salt',
    name: 'Tata Salt Vacuum Evaporated',
    nameHindi: 'टाटा नमक',
    category: 'Spices & Condiments',
    sku: 'SPC-SLT-06',
    quantity: 45,
    unit: 'packet',
    purchasePrice: 22,
    sellingPrice: 28,
    reorderLevel: 15,
    supplierName: 'Gupta Edible Oils & FMCG',
    supplierId: 'sup_002',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_butter',
    name: 'Amul Butter 500g',
    nameHindi: 'अमुल मक्खन',
    category: 'Dairy',
    sku: 'DRY-AMB-07',
    quantity: 9,
    unit: 'packet',
    purchasePrice: 245,
    sellingPrice: 285,
    reorderLevel: 5,
    supplierName: 'Gupta Edible Oils & FMCG',
    supplierId: 'sup_002',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_maggi',
    name: 'Maggi 2-Minute Masala Noodles',
    nameHindi: 'मैगी नूडल्स',
    category: 'Instant Food',
    sku: 'FMCG-MAG-08',
    quantity: 72,
    unit: 'packet',
    purchasePrice: 11.5,
    sellingPrice: 14,
    reorderLevel: 20,
    supplierName: 'Gupta Edible Oils & FMCG',
    supplierId: 'sup_002',
    updatedAt: new Date().toISOString(),
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust_ramesh',
    name: 'Ramesh Verma',
    phone: '+91 98101 23456',
    address: 'H-34, Gali No. 4, Govindpuri, Kalkaji',
    totalPurchases: 14500,
    amountPaid: 11200,
    amountPending: 3300,
    creditLimit: 8000,
    lastTransactionDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    notes: 'Regular customer, pays on 1st of every month via cash/UPI',
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'cust_suresh',
    name: 'Suresh Kumar',
    phone: '+91 98712 34567',
    address: 'Flat 202, Pocket B, Sarita Vihar',
    totalPurchases: 8400,
    amountPaid: 8400,
    amountPending: 0,
    creditLimit: 5000,
    lastTransactionDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    notes: 'Always pays immediately on UPI',
    createdAt: '2026-02-01T11:30:00Z',
  },
  {
    id: 'cust_priya',
    name: 'Priya Sharma',
    phone: '+91 99580 87654',
    address: 'B-12, Tehkhand Village, Okhla',
    totalPurchases: 6200,
    amountPaid: 4500,
    amountPending: 1700,
    creditLimit: 4000,
    lastTransactionDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    notes: 'School teacher nearby, weekly settlement',
    createdAt: '2026-02-10T14:15:00Z',
  },
  {
    id: 'cust_sunita',
    name: 'Sunita Gupta',
    phone: '+91 98119 54321',
    address: 'C-78, Alaknanda Appts, Kalkaji',
    totalPurchases: 22000,
    amountPaid: 18000,
    amountPending: 4000,
    creditLimit: 10000,
    lastTransactionDate: new Date(Date.now() - 12 * 86400000).toISOString(),
    notes: 'Payment overdue by 8 days, reminder queued',
    createdAt: '2026-01-18T09:00:00Z',
  },
  {
    id: 'cust_rajesh',
    name: 'Rajesh Mehra',
    phone: '+91 97170 11223',
    address: 'Plot 44, Harkesh Nagar, Okhla',
    totalPurchases: 3100,
    amountPaid: 3100,
    amountPending: 0,
    creditLimit: 3000,
    lastTransactionDate: new Date(Date.now() - 8 * 86400000).toISOString(),
    notes: 'Cash buyer',
    createdAt: '2026-02-15T16:45:00Z',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup_001',
    name: 'Sharma Wholesale Agro Mandi',
    phone: '+91 98990 01122',
    categories: ['Grains & Cereals', 'Staples', 'Pulses', 'Flour'],
    totalPurchased: 85000,
    amountPending: 12000,
    createdAt: '2026-01-15T08:30:00Z',
  },
  {
    id: 'sup_002',
    name: 'Gupta Edible Oils & FMCG',
    phone: '+91 98188 33445',
    categories: ['Edible Oils', 'Dairy', 'Instant Food', 'Spices & Condiments'],
    totalPurchased: 48000,
    amountPending: 4500,
    createdAt: '2026-01-16T12:00:00Z',
  },
];

export const initialSales: Sale[] = [
  {
    id: 'sale_101',
    invoiceNo: 'INV-2026-0101',
    customerId: 'cust_ramesh',
    customerName: 'Ramesh Verma',
    items: [
      { productId: 'prod_atta', productName: 'Chakki Fresh Atta', quantity: 10, unit: 'kg', unitPrice: 42, totalPrice: 420 },
      { productId: 'prod_sugar', productName: 'Refined Sugar M-Grade', quantity: 5, unit: 'kg', unitPrice: 46, totalPrice: 230 },
    ],
    totalAmount: 650,
    paidAmount: 0,
    balanceAmount: 650,
    paymentStatus: 'credit',
    paymentDueDate: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
    notes: 'Given on udhar, pay next week',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'sale_102',
    invoiceNo: 'INV-2026-0102',
    customerId: 'cust_suresh',
    customerName: 'Suresh Kumar',
    items: [
      { productId: 'prod_oil', productName: 'Fortune Mustard Oil Kacchi Ghani', quantity: 2, unit: 'litre', unitPrice: 165, totalPrice: 330 },
      { productId: 'prod_salt', productName: 'Tata Salt Vacuum Evaporated', quantity: 2, unit: 'packet', unitPrice: 28, totalPrice: 56 },
    ],
    totalAmount: 386,
    paidAmount: 386,
    balanceAmount: 0,
    paymentStatus: 'upi',
    notes: 'Paid via GPay',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'sale_103',
    invoiceNo: 'INV-2026-0103',
    customerId: 'cust_priya',
    customerName: 'Priya Sharma',
    items: [
      { productId: 'prod_butter', productName: 'Amul Butter 500g', quantity: 1, unit: 'packet', unitPrice: 285, totalPrice: 285 },
      { productId: 'prod_maggi', productName: 'Maggi 2-Minute Masala Noodles', quantity: 6, unit: 'packet', unitPrice: 14, totalPrice: 84 },
    ],
    totalAmount: 369,
    paidAmount: 0,
    balanceAmount: 369,
    paymentStatus: 'credit',
    paymentDueDate: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    notes: 'Pending udhar',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'sale_104',
    invoiceNo: 'INV-2026-0104',
    customerId: 'cust_sunita',
    customerName: 'Sunita Gupta',
    items: [
      { productId: 'prod_rice', productName: 'Basmati Rice Premium', quantity: 15, unit: 'kg', unitPrice: 60, totalPrice: 900 },
      { productId: 'prod_dal', productName: 'Toor Dal Desi Unpolished', quantity: 5, unit: 'kg', unitPrice: 170, totalPrice: 850 },
    ],
    totalAmount: 1750,
    paidAmount: 0,
    balanceAmount: 1750,
    paymentStatus: 'credit',
    paymentDueDate: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0], // Overdue!
    notes: 'Monthly grocery udhar',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
];

export const initialReceivables: Receivable[] = [
  {
    id: 'rec_001',
    customerId: 'cust_ramesh',
    customerName: 'Ramesh Verma',
    customerPhone: '+91 98101 23456',
    saleId: 'sale_101',
    invoiceNo: 'INV-2026-0101',
    totalAmount: 650,
    paidAmount: 0,
    remainingAmount: 650,
    dueDate: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
    status: 'pending',
    daysOverdue: 0,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'rec_002',
    customerId: 'cust_ramesh',
    customerName: 'Ramesh Verma',
    customerPhone: '+91 98101 23456',
    saleId: 'sale_past_ramesh',
    invoiceNo: 'INV-2026-0089',
    totalAmount: 2650,
    paidAmount: 0,
    remainingAmount: 2650,
    dueDate: new Date(Date.now() + 6 * 86400000).toISOString().split('T')[0],
    status: 'pending',
    daysOverdue: 0,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'rec_003',
    customerId: 'cust_priya',
    customerName: 'Priya Sharma',
    customerPhone: '+91 99580 87654',
    saleId: 'sale_103',
    invoiceNo: 'INV-2026-0103',
    totalAmount: 1700,
    paidAmount: 0,
    remainingAmount: 1700,
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    status: 'pending',
    daysOverdue: 0,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'rec_004',
    customerId: 'cust_sunita',
    customerName: 'Sunita Gupta',
    customerPhone: '+91 98119 54321',
    saleId: 'sale_104',
    invoiceNo: 'INV-2026-0104',
    totalAmount: 4000,
    paidAmount: 0,
    remainingAmount: 4000,
    dueDate: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
    status: 'overdue',
    daysOverdue: 4,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
];

export const initialTelemetry: ModelTelemetry = {
  totalRequests: 42,
  localLightweightRequests: 38,
  cloudLLMRequests: 4,
  estimatedTokensSaved: 18450,
  avgLatencyMs: 24,
  costSavedINR: 112.5,
};
